# Generated by Django 4.1.5 on 2023-01-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.IntegerField(verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=80, verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=200, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=100, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='name',
            field=models.CharField(max_length=200, verbose_name='theme'),
        ),
    ]
