# Generated by Django 4.1.5 on 2023-01-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_classes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='tag',
            field=models.ManyToManyField(default=None, to='main.tags'),
        ),
    ]
