# Generated by Django 4.1.5 on 2023-01-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_items_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='tag',
            field=models.ManyToManyField(blank=True, default=None, to='main.tags'),
        ),
    ]
